openapi: 3.0.0
info:
  title: 'Library API'
  version: '1.0.0'
  description: 'A simple Express Library API'

paths:
  /books:
    get:
      summary: Returns the list of all the books
      tags: [Books]
      responses:
        '200':
          description: The list of the books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      summary: Create a new book
      tags: [Books]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: The book was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '500':
          description: Some server error

  /books/{id}:
    get:
      summary: Get the book by id
      tags: [Books]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The book id
      responses:
        '200':
          description: The book description by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: The book was not found

    put:
      summary: Update the book by id
      tags: [Books]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The book id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: The book was updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: The book was not found
        '500':
          description: Some server error

    delete:
      summary: Remove the book by id
      tags: [Books]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The book id
      responses:
        '200':
          description: The book was deleted
        '404':
          description: The book was not found

components:
  schemas:
    Book:
      type: object
      required:
        - title
      properties:
        id:
          type: string
          description: The auto-generated id of the book
        title:
          type: string
          description: The book title
      example:
        id: 13
        title: Clean Code
