openapi: 3.0.0
info:
  title: 'Library API'
  version: '1.0.0'
  description: 'A simple Express Library API'

paths:
  /authors:
    get:
      summary: Returns the list of all the authors
      tags: [ Authors ]
      responses:
        '200':
          description: The list of the authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

    post:
      summary: Create a new author
      tags: [ Authors ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: The author was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

  /authors/{id}:
    get:
      summary: Get the author by id
      tags: [ Authors ]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The author id
      responses:
        '200':
          description: The author description by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: The author was not found

    put:
      summary: Update the author by id
      tags: [ Authors ]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The author id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: The author was updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: The author was not found
        '500':
          description: Some server error

    delete:
      summary: Remove the author by id
      tags: [ Authors ]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The author id
      responses:
        '200':
          description: The author was deleted
        '404':
          description: The author was not found

components:
  schemas:
    Author:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          description: The auto-generated id of the author
        name:
          type: string
          description: The author name
      example:
        id: 13
        title: Robert Martin
